### ISSUE TITLE
OPENAIBackend has not attribute "encode"

### ISSUE THREAD

**Issue by luqmanoxyz** [MaartenGr/BERTopic#1748]
Hi,

I am trying to use 'text-embedding-ada-002' as my embedding model. But i keep getting the error below when i try to run pre-calculated embeddings (it seems like 'encode' does not work with the openai>1.0 library):

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-22-a6278a2c526f>](https://localhost:8080/#) in <cell line: 6>()
      4 client = openai.OpenAI()
      5 embedding_model = OpenAIBackend(client, "text-embedding-ada-002")
----> 6 embeddings = embedding_model.encode(reviews, show_progress_bar=True)

AttributeError: 'OpenAIBackend' object has no attribute 'encode'

**Comment by MaartenGr** [comment]
You should use the latest commit in the main branch as this was fixed there I believe.
