### ISSUE TITLE
pip install on new environment is not working on python 3.8.13

### ISSUE THREAD

**Issue by mikelam14** [MaartenGr/BERTopic#741]
I am trying to follow the guide by
```
from bertopic import BERTopic
topic_model = BERTopic()
topic_model.fit_transform(["abcde", "doc2"])
```
First I ran into an issue from hdbscan
```
Python 3.8.13 (default, Mar 28 2022, 06:16:26)
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
imp>>> import bertopic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "opt/anaconda3/envs/bertopic/lib/python3.8/site-packages/bertopic/__init__.py", line 1, in <module>
    from bertopic._bertopic import BERTopic
  File "/opt/anaconda3/envs/bertopic/lib/python3.8/site-packages/bertopic/_bertopic.py", line 23, in <module>
    import hdbscan
  File "/opt/anaconda3/envs/bertopic/lib/python3.8/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/opt/anaconda3/envs/bertopic/lib/python3.8/site-packages/hdbscan/hdbscan_.py", line 509, in <module>
    memory=Memory(cachedir=None, verbose=0),
TypeError: __init__() got an unexpected keyword argument 'cachedir'
```
I got around this by downgrading joblib to 1.1.0

Secondly when i run this again, I saw omp_set_nested routine depecrecated. I got around this by installing numba==0.56.2
```>>> topic_model = BERTopic()
>>> # topic_model.fit_transform(docs[:10])
>>> topic_model.fit_transform(["abcde", "doc2"])
OMP: Info #271: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
[1]    6204 segmentation fault  python
/Users/mikelam/opt/anaconda3/envs/bertopic/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

Lastly when i ran this again, it went straight to segfault. 
```
>>> from bertopic import BERTopic
>>> topic_model = BERTopic()
>>> # topic_model.fit_transform(docs[:10])
>>> topic_model.fit_transform(["abcde", "doc2"])
[1]    6660 segmentation fault  python
```

How can I successfully try the package out?

**Comment by MaartenGr** [comment]
It might have something to do with the number of documents that you fit the model on. 2 documents are rather shallow, I would suggest fitting on at least a couple of hundred documents.

**Comment by mikelam14** [comment]
I actually tried with 10, 100, 10000 documents. They all cause segfault.

**Comment by MaartenGr** [comment]
Perhaps it is related to your environment. Could you try starting from a completely fresh environment and installing the newest version of BERTopic there?

**Comment by issam9** [comment]
The solution in this [stackoverflow post](https://stackoverflow.com/questions/73830225/init-got-an-unexpected-keyword-argument-cachedir-when-importing-top2vec) solved the problem for me. Which is to install an older version of joblib before cachedir was removed

**Comment by mikelam14** [comment]
@MaartenGr This is already a completely fresh environment, python 3.8.13, bertopic==0.12.0

@issam9 Yes I referred to this post for solving the cachedir problem. Thank you. My subsequence problems remain unsolved.

**Comment by MaartenGr** [comment]
I am not entirely sure but there might be two things happening here. First, there might be an issue with you [python version in conda](https://github.com/conda/conda/issues/9589). Second, I believe there is an issue with the [newest version of numba](https://github.com/numba/numba/issues/5520) that you are using so installing an earlier version might just do the trick.

**Comment by VinayChaudhari1996** [comment]
It worked for me 
```
!pip install --upgrade joblib==1.1.0
```

**Comment by tisRobin** [comment]
@mikelam14 

May I ask how you wrote the script to solve the cachedir problem? 

I tried this too but its not working for me. I tried writing: 

`
!pip install --upgrade joblib==1.1.0
`
`
!pip install bertopic
`
`
from bertopic import BERTopic
`

**Comment by MaartenGr** [comment]
Make sure to install the correct joblib version in the right order:

```python
!pip install bertopic
!pip install --upgrade joblib==1.1.0
from bertopic import BERTopic
```

You can also find more about the issues with 1.1.0 and HDBSCAN [here](https://github.com/scikit-learn-contrib/hdbscan/issues/562) and [here](https://github.com/scikit-learn-contrib/hdbscan/issues/565)
