### ISSUE TITLE
TypeError: visualize_barchart() got an unexpected keyword argument 'title'

### ISSUE THREAD

**Issue by TeTeTang** [MaartenGr/BERTopic#1055]
Got the unexpected keyword argument error on topic_model.visualize_barchart(top_n_topics=10, n_words=8, title="Topic Word Scores For Reviews")

But 'title' seems like a legitimate argument in 
def visualize_barchart(self,
                           topics: List[int] = None,
                           top_n_topics: int = 8,
                           n_words: int = 5,
                           custom_labels: bool = False,
                           title: str = "Topic Word Scores",
                           width: int = 250,
                           height: int = 250) -> go.Figure:

**Comment by MaartenGr** [comment]
Strange, it should be there. Which version of BERTopic are you currently using?

**Comment by TeTeTang** [comment]
I believe I'm using 0.9.4. Will it be a problem? I'll install the latest version and see if the issue will be resolved.

**Comment by TeTeTang** [comment]
Successfully installed bertopic-0.14.1 hdbscan-0.8.29 => TypeError: visualize_barchart() got an unexpected keyword argument 'topic', The error was still there after upgrading bertopic to 0.14.1.

**Comment by TeTeTang** [comment]
Sorry, my bad, I meant the 'title' argument, not 'topics'. I used the 'topics' argument to customize plot title carelessly. The problem has been addressed after upgrading BERTopic. Thank you!
