### ISSUE TITLE
Cachedir error

### ISSUE THREAD

**Issue by miggytrinidad** [MaartenGr/BERTopic#730]
Any solution to this error?

TypeError: __init__() got an unexpected keyword argument 'cachedir'

**Comment by Sct-ctrl** [comment]
I had that error too. I downgraded joblib to 1.1.0 (https://anaconda.org/anaconda/joblib) and was able to import bertopic without error. I need to test it more.

**Comment by MaartenGr** [comment]
Based on your error message, the [recent commit](https://github.com/scikit-learn-contrib/hdbscan/pull/563) in the HDBSCAN repo, and that joblib was recently [updated](https://pypi.org/project/joblib/#history), it seems that the problem should be resolved by either installing HDBSCAN from its main branch or by installing a previous version of joblib after installing BERTopic:

 `pip install --upgrade joblib==1.1.0`

**Comment by miggytrinidad** [comment]
Thanks!

**Comment by kannaxp-git** [comment]
What are the right versions of hdbscan and joblib for bertopic to work??

**Comment by MaartenGr** [comment]
@kannaxp-git You can use the latest version of HDBSCAN bas long as you make sure that joblib is version 1.1.0 or less. It is likely that previous versions of HDBSCAN will also only work with joblib 1.1.0 or less.

**Comment by kannaxp-git** [comment]
Hi Marrten,

Thanks for getting back to me, yes i managed to run bertopic with previous version of hdbscan/joblib  by going through the issues conversation history.

but now the problem is fit_transform is running forever, i am not sure whether it is normal or anything wrong with my installation.

FYI: i am running the sample code from github repo with newsgroups data
[cid:736a1f26-fd5b-4779-9d7f-26ce8515c197]


|< /\ |\| |\| /\ |\|
 Sr Data Scientist, Microsoft.
________________________________

**Comment by MaartenGr** [comment]
@kannaxp-git Could you share your exact code for training your BERTopic model? That way, it is a bit easier to see if the problem might be related to the code. Also, did you try installing BERTopic from a completely fresh environment?

**Comment by MaartenGr** [comment]
To those looking for a permanent solution, it seems that a new version of HDBSCAN was pushed to pypi with the fix for the cachidir error. This means that it should run without problems using `pip install --upgrade hdbscan`. In the next release of BERTopic, the dependencies will be fixed but since it typically already takes the most recent version of packages it should work without any problems.
