### ISSUE TITLE
TypeError when importing BERTopic object

### ISSUE THREAD

**Issue by abdelatifsd** [MaartenGr/BERTopic#288]
Hello:)

After pip installing the library, importing from the module (running "from bertopic import BERTopic") leads to the following error: TypeError: load() missing 1 required positional argument: 'Loader'

Thanks!

**Comment by MaartenGr** [comment]
Strange, I just tested out some things and it turns out that the entire `distributed` package is giving issues. Just installing BERTopic in a Google Colab environment results in errors. Although this seems to be related to the `distributed` package, I do not believe it is a dependency within BERTopic that is causing the issue. For example, when I install BERTopic in an environment in which `distributed` is not installed, `distributed` will not be installed. 

After some testing, it seems that `distributed==1.25.3` is the issue here since the following fixes are working for me.

### **Fixes**

First, with `distributed==2021.9.0`:

```
!pip install bertopic
!pip install distributed==2021.9.0
```

Second, it actually works with `distributed==2021.9.1`:

```
!pip install bertopic
!pip install distributed==2021.9.1
```

Third, it works by fully uninstalling `distributed`:

```
!pip install bertopic
!pip uninstall distributed
```

### **Source of the Issue**  
It seems that I can reproduce the error by uninstalling  `distributed==1.25.3` and then re-install it again  `distributed==1.25.3`:

```
!pip install bertopic
!pip uninstall distributed
!pip install distributed==1.25.3
```

This means that I would advise either upgrading `distributed` or simply uninstalling it as it does not seem to impact the functionality of BERTopic. 

### **New release**
In the new release, I am likely just inserting `distributed>1.25.3` in the requirements to make sure that version is not used. I would also need to make sure what the minimum version is needed for it to work. For example, 1.25.4 may also not work.
